export const R = {
  HT: /(?:(?:total|montant|sous[\s\-]?total)\s*HT)\s*[:\-]?\s*([0-9\s\.,]+)\s*€?/gi,
  TVA_PCT: /TVA\s*[:\-]?\s*(\d{1,2}[\.,]?\d{0,2})\s*%/gi,
  TVA_AMT: /TVA\s*(?:\(.*?\))?\s*[:\-]?\s*([0-9\s\.,]+)\s*€?/gi,
  TTC: /(?:(?:total|montant)\s*TTC)\s*[:\-]?\s*([0-9\s\.,]+)\s*€?/gi,
  NET: /net\s*(?:à|a)\s*payer\s*[:\-]?\s*([0-9\s\.,]+)\s*€?/gi,
  SIRET: /\b\d{3}\s?\d{3}\s?\d{3}\s?\d{5}\b/gi,
  SIREN: /\b\d{3}\s?\d{3}\s?\d{3}\b/gi,
  NUM_FACT: /(?:n[°o]\s*[:\-]?\s*|facture\s*[:\-]?\s*)([A-Z0-9\-\/]+)/gi,
  DATE: /\b([0-3]?\d[\/\-\.][01]?\d[\/\-\.]\d{2,4})\b/g,
  EUR: /€/,
  AO_DEADLINE: /date\s*limite.*?([0-3]?\d[\/\-\.][01]?\d[\/\-\.]\d{2,4})/gi,
  AO_CP: /\b(0[1-9]|[1-8]\d|9[0-5])\d{3}\b/g,
  AO_BUDGET: /(?:montant|budget)\s*(?:estim[ée]s?)?\s*[:\-]?\s*([0-9\s\.,]+)\s*€?/gi,
  AO_REF: /(?:réf\.|référence)\s*[:\-]?\s*([A-Z0-9\-\/]+)/gi,
  AO_ORGA: /(?:organisme|acheteur|maître d['']ouvrage|pouvoir adjudicateur)\s*[:\-]?\s*(.+)/gi,
  FOURNISSEUR: /(?:société|entreprise|sa|sarl|sas|eurl)\s+([A-Z][A-Za-z\s\-&]+)/gi,
};
